# Generated by Django 6.0.5 on 2026-05-10 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#dc143c', max_length=7, verbose_name='اللون الأساسي')),
                ('company_name_color', models.CharField(default='#dc143c', max_length=7, verbose_name='لون اسم الشركة')),
                ('show_logo', models.BooleanField(default=True, verbose_name='إظهار الشعار')),
                ('show_footer', models.BooleanField(default=True, verbose_name='إظهار التذييل')),
                ('footer_message', models.CharField(default='شكراً لتسوقكم معنا', max_length=200, verbose_name='رسالة التذييل')),
                ('invoice_title', models.CharField(default='فاتورة', max_length=50, verbose_name='عنوان الفاتورة')),
                ('font_family', models.CharField(default='Tajawal', max_length=50, verbose_name='الخط')),
                ('header_size', models.IntegerField(default=20, verbose_name='حجم اسم الشركة')),
                ('border_style', models.CharField(choices=[('solid', 'Solid'), ('dashed', 'Dashed'), ('dotted', 'Dotted')], default='solid', max_length=20, verbose_name='نمط الحدود')),
                ('custom_css', models.TextField(blank=True, help_text='كود CSS إضافي لتخصيص تصميم الفاتورة', null=True, verbose_name='CSS مخصص')),
            ],
            options={
                'verbose_name': 'تصميم الفاتورة',
                'verbose_name_plural': 'تصميم الفاتورة',
            },
        ),
    ]
