# Generated by Django 6.0.5 on 2026-05-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_default_roles_and_landing'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicetemplate',
            name='phone',
            field=models.CharField(blank=True, help_text='رقم الهاتف الظاهر أسفل اسم الشركة', max_length=30, null=True, verbose_name='رقم الهاتف'),
        ),
    ]
