# Generated by Django 6.0.5 on 2026-05-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_invoicetemplate_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='website',
            field=models.URLField(blank=True, help_text='مثال: https://playbaby.com', null=True, verbose_name='الموقع الإلكتروني'),
        ),
    ]
