# Generated by Django 6.0.5 on 2026-05-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sitesetting_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicetemplate',
            name='phone_color',
            field=models.CharField(default='#888888', help_text='مثال: #888888', max_length=7, verbose_name='لون نص الترويسة'),
        ),
        migrations.AddField(
            model_name='invoicetemplate',
            name='phone_font_size',
            field=models.IntegerField(default=11, help_text='حجم الخط (8-30)', verbose_name='حجم نص الترويسة'),
        ),
        migrations.AlterField(
            model_name='invoicetemplate',
            name='footer_message',
            field=models.TextField(default='شكراً لتسوقكم معنا', help_text='نص التذييل (يدعم عدة أسطر)', verbose_name='رسالة التذييل'),
        ),
        migrations.AlterField(
            model_name='invoicetemplate',
            name='phone',
            field=models.TextField(blank=True, help_text='نص يظهر أسفل اسم الشركة (يدعم عدة أسطر)', null=True, verbose_name='نص الترويسة'),
        ),
    ]
