# Generated by Django 6.0.5 on 2026-05-09 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('color', models.CharField(default='#6c757d', help_text='مثال: #28a745', max_length=7, verbose_name='اللون')),
            ],
            options={
                'verbose_name': 'حالة الفاتورة',
                'verbose_name_plural': 'حالات الفواتير',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
            ],
            options={
                'verbose_name': 'طريقة دفع',
                'verbose_name_plural': 'طرق الدفع',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.invoicestatus', verbose_name='الحالة'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.paymentmethod', verbose_name='طريقة الدفع'),
        ),
    ]
