# Generated by Django 6.0.5 on 2026-05-09 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoicestatus_paymentmethod_invoice_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoicestatus',
            options={'ordering': ['order'], 'verbose_name': 'حالة الطلب', 'verbose_name_plural': 'حالات الطلبات'},
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.invoicestatus', verbose_name='حالة الطلب'),
        ),
    ]
