# Generated by Django 6.0.5 on 2026-05-10 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_invoice_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='خصم على الفاتورة %'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='خصم %'),
        ),
    ]
