# Generated by Django 6.0.5 on 2026-05-10 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_invoice_discount_percent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='cancel_reason',
            field=models.TextField(blank=True, null=True, verbose_name='سبب الإلغاء'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإلغاء'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_cancelled',
            field=models.BooleanField(default=False, verbose_name='ملغي'),
        ),
        migrations.CreateModel(
            name='InvoiceStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التغيير')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم بواسطة')),
                ('from_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='invoices.invoicestatus', verbose_name='من حالة')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='invoices.invoice', verbose_name='الفاتورة')),
                ('to_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='invoices.invoicestatus', verbose_name='إلى حالة')),
            ],
            options={
                'verbose_name': 'سجل حالة الطلب',
                'verbose_name_plural': 'سجل حالات الطلبات',
                'ordering': ['-changed_at'],
            },
        ),
    ]
