# Generated by Django 6.0.5 on 2026-05-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('invoices', '0006_invoice_cancel_reason_invoice_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicestatus',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, to='auth.group', verbose_name='المجموعات المسموحة'),
        ),
    ]
