# Generated by Django 6.0.5 on 2026-05-10 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_invoicestatus_allowed_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='revision_status',
            field=models.CharField(choices=[('pending_shipping', 'بانتظار تأكيد الشحن'), ('shipping_confirmed', 'تم تأكيد الشحن'), ('pending_approval', 'بانتظار موافقة المبيعات'), ('approved', 'تمت الموافقة'), ('rejected', 'مرفوض')], default='pending_shipping', max_length=20, verbose_name='حالة المراجعة'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='confirmed_quantity',
            field=models.IntegerField(blank=True, help_text='تؤكد من قبل الشحن', null=True, verbose_name='الكمية المؤكدة'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_invoice', 'فاتورة جديدة'), ('availability_confirmed', 'تم تأكيد التوفر'), ('revision_approved', 'تمت الموافقة على المراجعة'), ('revision_rejected', 'تم رفض المراجعة'), ('needs_approval', 'بانتظار الموافقة')], max_length=30, verbose_name='النوع')),
                ('message', models.TextField(blank=True, verbose_name='الرسالة')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروء')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='invoices.invoice', verbose_name='الفاتورة')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستلم')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='المرسل')),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
                'ordering': ['-created_at'],
            },
        ),
    ]
