# Generated by Django 6.0.5 on 2026-05-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_invoice_item_confirmed_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_invoice', 'فاتورة جديدة'), ('availability_confirmed', 'تم تأكيد التوفر'), ('revision_approved', 'تمت الموافقة على المراجعة'), ('revision_rejected', 'تم رفض المراجعة'), ('needs_approval', 'بانتظار الموافقة'), ('cancelled', 'إلغاء')], max_length=30, verbose_name='النوع'),
        ),
    ]
