# Generated by Django 6.0.5 on 2026-05-10 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='collected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التحصيل'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='collected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_invoices', to=settings.AUTH_USER_MODEL, verbose_name='تم التحصيل بواسطة'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_collected',
            field=models.BooleanField(default=False, verbose_name='تم التحصيل'),
        ),
    ]
